# Auto-assign configuration for pull requests
addReviewers: true
addAssignees: false

# Reviewers to be added when a PR is opened
reviewers:
  - Ruixiaoke

# Assignees to be added when a PR is opened (if addAssignees is true)
assignees: []

# Number of reviewers to add
numberOfReviewers: 1

# Number of assignees to add
numberOfAssignees: 0

# Skip adding reviewers/assignees if PR author is in this list
skipKeywords:
  - WIP
  - wip
  - draft

# Add reviewers based on file patterns
fileBasedReviewers:
  # Python MCP server changes
  'MCP_servers/ASimpleStargGazer_python/**':
    - Ruixiaoke
  
  # .NET MCP server changes  
  'MCP_servers/ASimpleStargGazer_dotnet/**':
    - Ruixiaoke
    
  # Node.js MCP server changes
  'MCP_servers/ASimpleStargGazer_node/**':
    - Ruixiaoke
    
  # Frontend changes
  'ASimpleStargGazer_frontend/**':
    - Ruixiaoke
    
  # Infrastructure changes
  'ASimpleStargGazer_Infra/**':
    - Ruixiaoke
    
  # CI/CD changes
  '.github/**':
    - Ruixiaoke
    
  # Documentation changes
  'docs/**':
    - Ruixiaoke
  'README.md':
    - Ruixiaoke